name: "Static analysis"

on:
  workflow_call: ~
  workflow_dispatch: ~

jobs:
  static-analysis:
    name: "static analysis"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            vendor
          key: ${{ runner.os }}-php-8.5-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.5-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Running static analysis
        run: ./tools/bin/project/project psalm

      - name: Calculating type coverage
        run: ./tools/bin/project/project type-coverage
